"""Auto update

Revision ID: 112d1cc8bf97
Revises: 19a3c0e764aa
Create Date: 2025-09-02 14:48:43.457683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112d1cc8bf97'
down_revision: Union[str, None] = '19a3c0e764aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'to_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'parent_reference_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('parent_reference_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('transactions', 'to_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'from_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
