"""Auto update

Revision ID: 596ea7e08a8f
Revises: d2d62f314f47
Create Date: 2025-08-28 11:48:44.311759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596ea7e08a8f'
down_revision: Union[str, None] = 'd2d62f314f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_types_pkey')),
    sa.UniqueConstraint('type_code', name=op.f('wallet_types_type_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
