"""Auto update

Revision ID: 5a5c15881875
Revises: 112d1cc8bf97
Create Date: 2025-09-02 14:51:53.247783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5c15881875'
down_revision: Union[str, None] = '112d1cc8bf97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_reference_code'), table_name='transactions')
    op.create_index(op.f('ix_transactions_reference_code'), 'transactions', ['reference_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_reference_code'), table_name='transactions')
    op.create_index(op.f('ix_transactions_reference_code'), 'transactions', ['reference_code'], unique=True)
    # ### end Alembic commands ###
