"""Auto update

Revision ID: a89977caa522
Revises: 8f084756c232
Create Date: 2025-08-27 15:27:20.187097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89977caa522'
down_revision: Union[str, None] = '8f084756c232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'users', ['p'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'p')
    # ### end Alembic commands ###
