"""Auto update

Revision ID: ca0195c6d41e
Revises: a1ceff6fc7ac
Create Date: 2025-08-27 15:20:06.166928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0195c6d41e'
down_revision: Union[str, None] = 'a1ceff6fc7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
