"""Auto update

Revision ID: d2d62f314f47
Revises: a89977caa522
Create Date: 2025-08-27 15:27:33.284318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d62f314f47'
down_revision: Union[str, None] = 'a89977caa522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_p_key'), 'users', type_='unique')
    op.drop_column('users', 'p')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_p_key'), 'users', ['p'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
